### PR TITLE
Explain minimal host /2

### LINKED ISSUE #28927: Add note about UseRateLimiter() order of statement in relation to UseRouting()
Could you please indicate in the document the order of where to place `app.UseRateLimiter()` in the program/startup is important in relation to `app.UseRouting()` (i.e. after it) or RateLimiting will not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bb96b20f-0991-d6de-4d98-192cd469460f
* Version Independent ID: bb96b20f-0991-d6de-4d98-192cd469460f
* Content: [Rate limiting middleware in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/performance/rate-limit?view=aspnetcore-7.0)
* Content Source: [aspnetcore/performance/rate-limit.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/performance/rate-limit.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 85543](https://dev.azure.com/msft-skilling/Content/_workitems/edit/85543)

### LINKED ISSUE #28978: Add info about WebApplication  as a Host
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1b97662b-2954-2af6-2980-ef031890ff9f
* Version Independent ID: 1b97662b-2954-2af6-2980-ef031890ff9f
* Content: [WebApplication and WebApplicationBuilder in Minimal API apps](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/webapplication?view=aspnetcore-7.0)
* Content Source: [aspnetcore/fundamentals/minimal-apis/webapplication.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/minimal-apis/webapplication.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 85487](https://dev.azure.com/msft-skilling/Content/_workitems/edit/85487)

### PR DESCRIPTION
**Pull request by Rick-Anderson**
Fixes #28927
Fixes #28978

Changes:

* aspnetcore/fundamentals/minimal-apis/middleware.md moved to an include file so it can be also be used in the hosting doc.
* If `UseRouting` is called, `UseRateLimiter` must be called after `UseRouting`.

Internal previews

* [Middleware order](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?branch=pr-en-us-28979&view=aspnetcore-7.0#middleware-order) then search for `UseRateLimiter`
* [Middleware in Minimal API apps](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/middleware?branch=pr-en-us-28979) Doc Unchanged - previous content moved to an include file.
* [WebApplication and WebApplicationBuilder in Minimal API apps](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/webapplication?branch=pr-en-us-28979)  Added include here also, hosting doc should have this info.

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/fundamentals/middleware/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/18610a142fd0b9204fc7a235e7a1518d517f5164/aspnetcore/fundamentals/middleware/index.md) | [ASP.NET Core Middleware](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/middleware/index?branch=pr-en-us-28979) |
| [aspnetcore/fundamentals/minimal-apis/middleware.md](https://github.com/dotnet/AspNetCore.Docs/blob/18610a142fd0b9204fc7a235e7a1518d517f5164/aspnetcore/fundamentals/minimal-apis/middleware.md) | [Middleware in Minimal API apps](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/middleware?branch=pr-en-us-28979) |
| [aspnetcore/fundamentals/minimal-apis/webapplication.md](https://github.com/dotnet/AspNetCore.Docs/blob/18610a142fd0b9204fc7a235e7a1518d517f5164/aspnetcore/fundamentals/minimal-apis/webapplication.md) | [WebApplication and WebApplicationBuilder in Minimal API apps](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/webapplication?branch=pr-en-us-28979) |
| [aspnetcore/performance/rate-limit.md](https://github.com/dotnet/AspNetCore.Docs/blob/18610a142fd0b9204fc7a235e7a1518d517f5164/aspnetcore/performance/rate-limit.md) | [Rate limiting middleware in ASP.NET Core](https://review.learn.microsoft.com/en-us/aspnet/core/performance/rate-limit?branch=pr-en-us-28979) |

### CODE REVIEW

File: aspnetcore/fundamentals/middleware/index/snapshot/Program70All3.cs [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
+    app.UseHsts();
+}
+
+app.UseHttpsRedirection();
+app.UseStaticFiles();
+// app.UseCookiePolicy();
+
+app.UseRouting();
+// app.UseRateLimiter();
```
Comment (Rick-Anderson) [inline aspnetcore/fundamentals/middleware/index/snapshot/Program70All3.cs:36]: The 7.0 and higher versions adds this line to show the right order.

**Comment by Rick-Anderson** [comment]
@BrennanConroy  please review
Internal previews

* [Middleware order](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?branch=pr-en-us-28979&view=aspnetcore-7.0#middleware-order) then search for `UseRateLimiter`
* [Middleware in Minimal API apps](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/middleware?branch=pr-en-us-28979) Doc Unchanged - previous content moved to an include file.
* [WebApplication and WebApplicationBuilder in Minimal API apps](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/webapplication?branch=pr-en-us-28979)  Added include here also, hosting doc should have this info.
* [One line above this link]([WebApplication and WebApplicationBuilder in Minimal API apps](https://review.learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/webapplication?branch=pr-en-us-28979))

File: aspnetcore/fundamentals/middleware/index.md [hunk 2]
```diff
@@ -91,15 +91,16 @@ The order that middleware components are added in the `Program.cs` file defines
...
+[!code-csharp[](index/snapshot/Program70All3.cs?highlight=19-44)]
 
 In the preceding code:
 
 * Middleware that is not added when creating a new web app with [individual users accounts](xref:security/authentication/identity) is commented out.
 * Not every middleware appears in this exact order, but many do. For example:
   * `UseCors`, `UseAuthentication`, and `UseAuthorization` must appear in the order shown.
   * `UseCors` currently must appear before `UseResponseCaching`. This requirement is explained in [GitHub issue dotnet/aspnetcore #23218](https://github.com/dotnet/aspnetcore/issues/23218).
-  * `UseRequestLocalization` must appear before any middleware that might check the request culture (for example, `app.UseMvcWithDefaultRoute()`).
+  * `UseRequestLocalization` must appear before any middleware that might check the request culture, for example, `app.UseMvcWithDefaultRoute`.
```
Comment (JamesNK) [inline aspnetcore/fundamentals/middleware/index.md:102]: nit: `UseMvcWithDefaultRoute` is a very old API that has been replaced with endpoint routing. I think a more relevant example is needed.

Sorry, I don't know what middleware uses request culture off the top of my head.

File: aspnetcore/fundamentals/middleware/index.md [hunk 3]
```diff
@@ -91,15 +91,16 @@ The order that middleware components are added in the `Program.cs` file defines
...
+  * <xref:Microsoft.AspNetCore.Builder.RateLimiterApplicationBuilderExtensions.UseRateLimiter%2A> must be called after `UseRouting`.
```
Comment (JamesNK) [inline aspnetcore/fundamentals/middleware/index.md:103]: @BrennanConroy There are analyzers for checking middleware is registered in the right order. Have they been updated or tested with recent changes?

Comment (BrennanConroy) [reply aspnetcore/fundamentals/middleware/index.md:103]: UseRateLimiter only needs to be called after UseRouting if you use endpoint specific APIs, e.g. `EnableRateLimitingAttribute`.

If you use just the global limiter then it can run before UseRouting.

File: aspnetcore/fundamentals/middleware/index.md [hunk 4]
```diff
@@ -99,8 +99,8 @@ In the preceding code:
 * Not every middleware appears in this exact order, but many do. For example:
   * `UseCors`, `UseAuthentication`, and `UseAuthorization` must appear in the order shown.
   * `UseCors` currently must appear before `UseResponseCaching`. This requirement is explained in [GitHub issue dotnet/aspnetcore #23218](https://github.com/dotnet/aspnetcore/issues/23218).
-  * `UseRequestLocalization` must appear before any middleware that might check the request culture, for example, `app.UseMvcWithDefaultRoute`.
-  * <xref:Microsoft.AspNetCore.Builder.RateLimiterApplicationBuilderExtensions.UseRateLimiter%2A> must be called after `UseRouting` when rate limiting endpoint specific APIs are used. For example, if the [`[EnableRateLimiting]`](xref:Microsoft.AspNetCore.RateLimiting.EnableRateLimitingAttribute) Attribute is used, `UseRateLimiter` must be called after `UseRouting`.
+  * `UseRequestLocalization` must appear before any middleware that might check the request culture, for example, `app.MapControllerRoute`.
```
Comment (JamesNK) [inline aspnetcore/fundamentals/middleware/index.md:102]: MapControllerRoute isn't middleware. It configures routing.

UseRouting could certainly execute endpoints that use localization. It could be used as an example, but minimal host usually automatically adds it for you.

Comment (Rick-Anderson) [reply aspnetcore/fundamentals/middleware/index.md]: > MapControllerRoute isn't middleware. It configures routing.

Arg, either is `UseMvcWithDefaultRoute`, and it's not an old API either.

**Review by Rick-Anderson — COMMENTED** [review]
@JamesNK 
Check last commit

File: aspnetcore/fundamentals/middleware/index.md (hunk 4 above)
Comment (JamesNK) [reply aspnetcore/fundamentals/middleware/index.md]: `UseMvcWithDefaultRoute` is registering middleware.

It hasn't been obsoleted, but `MapDefaultControllerRoute` is the replacement that people should be using.

File: aspnetcore/fundamentals/middleware/index.md [hunk 5]
```diff
@@ -91,15 +91,16 @@ The order that middleware components are added in the `Program.cs` file defines
...
+[!code-csharp[](index/snapshot/Program70All3.cs?highlight=19-44)]
 
 In the preceding code:
 
 * Middleware that is not added when creating a new web app with [individual users accounts](xref:security/authentication/identity) is commented out.
 * Not every middleware appears in this exact order, but many do. For example:
   * `UseCors`, `UseAuthentication`, and `UseAuthorization` must appear in the order shown.
   * `UseCors` currently must appear before `UseResponseCaching`. This requirement is explained in [GitHub issue dotnet/aspnetcore #23218](https://github.com/dotnet/aspnetcore/issues/23218).
-  * `UseRequestLocalization` must appear before any middleware that might check the request culture (for example, `app.UseMvcWithDefaultRoute()`).
+  * `UseRequestLocalization` must appear before any middleware that might check the request culture, for example, <xref:Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware> or a custom middleware that checks request culture..
```
Comment (JamesNK) [inline aspnetcore/fundamentals/middleware/index.md:102]:
```suggestion
  * `UseRequestLocalization` must appear before any middleware that might check the request culture, for example, `app.UseStaticFiles()`.
```
I looked around and static files is an example of middleware that uses request culture.
