### PR TITLE
What's new IFORM /7

### LINKED ISSUE #30833: IFormFile WN
### Description

LInk to [here](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-8.0&branch=pr-en-us-30832#secure-binding-from-iformfile-and-iformfilecollection)

See #30644

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?view=aspnetcore-7.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/release-notes/aspnetcore-8.0.md

### Document ID

f30dbb9e-d64d-a925-01ca-00d9d035e6c1

### Article author

Rick-Anderson

---
[Associated WorkItem - 173847](https://dev.azure.com/msft-skilling/Content/_workitems/edit/173847)

### LINKED ISSUE #30853: Binding to forms with IFormCollection
### Description

When I run the code in [Binding to forms with IFormCollection, IFormFile, and IFormFileCollection](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/parameter-binding?preserve-view=true&view=aspnetcore-8.0#binding-to-forms-with-iformcollection-iformfile-and-iformfilecollection) it throws
```
InvalidOperationException: Endpoint HTTP: POST /upload contains anti-forgery metadata, 
but a middleware was not found that supports anti-forgery.
Configure your application startup by adding app.UseAntiforgery() in the application 
startup code. If there are calls to app.UseRouting() and app.UseEndpoints(...), 
the call to app.UseAntiforgery() must go between them. 
Calls to app.UseAntiforgery() must be placed after calls to app.UseAuthentication()
 and app.UseAuthorization().
```

It was working on May 22 in #29312

Need to combine that section with [Secure binding from IFormFile and IFormFileCollection](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/parameter-binding?preserve-view=true&view=aspnetcore-8.0#secure-binding-from-iformfile-and-iformfilecollection)

@andrewlock  please review

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/parameter-binding?branch=main&branchFallbackFrom=pr-en-us-29312&view=aspnetcore-7.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/minimal-apis/parameter-binding.md

### Document ID

a09dcf06-a685-e5b8-0ce4-a4e53c57a9fd

### Article author

Rick-Anderson

---
[Associated WorkItem - 174296](https://dev.azure.com/msft-skilling/Content/_workitems/edit/174296)

### PR DESCRIPTION
**Pull request by Rick-Anderson**
Fixes #30853
Fixes #30833

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/4934efd807c42ac471f513a3feaafcb9d8c4cf0a/aspnetcore/release-notes/aspnetcore-8.0.md) | [What's new in ASP.NET Core 8.0](https://review.learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?branch=pr-en-us-30854) |

### CODE REVIEW

File: aspnetcore/fundamentals/minimal-apis/parameter-binding/samples8/Iform/Program.cs [hunk 1]
```diff
@@ -6,6 +6,7 @@
 builder.Services.AddAntiforgery();
 
 var app = builder.Build();
+app.UseAntiforgery();
```
Comment (Rick-Anderson) [inline aspnetcore/fundamentals/minimal-apis/parameter-binding/samples8/Iform/Program.cs:9]: @andrewlock  this fixes #30853

File: aspnetcore/fundamentals/minimal-apis/parameter-binding/samples8/Iform/Program.cs [hunk 2]
```diff
@@ -43,17 +44,9 @@ async Task UploadFileWithName(IFormFile file, string fileSaveName)
 app.MapPost("/upload", async Task<Results<Ok<string>,
    BadRequest<string>>> (IFormFile file, HttpContext context, IAntiforgery antiforgery) =>
 {
-    try
-    {
-        await antiforgery.ValidateRequestAsync(context);
         var fileSaveName = Guid.NewGuid().ToString("N") + Path.GetExtension(file.FileName);
         await UploadFileWithName(file, fileSaveName);
         return TypedResults.Ok("File uploaded successfully!");
```
Comment (tdykstra) [inline aspnetcore/fundamentals/minimal-apis/parameter-binding/samples8/Iform/Program.cs:49]: This was wrapped in a try/catch block and when the try/catch code was removed, the indentation wasn't adjusted.

**Review by tdykstra — APPROVED** [review]
Looks good aside from one issue with code indentation.
