### PR TITLE
use xunit exception assertions in grpc integration test sample

### LINKED ISSUE #26937: GRPC MockedGreeterServiceTests sample tests do not work out-of-the-box
[Edit by guardrex to add the metadata.]

# Issue description

The [`SayHelloUnaryTest_MockGreeter_Error()`](https://github.com/dotnet/AspNetCore.Docs/blob/61d48b225d0611d176d6ad4367ea50ae841b30f6/aspnetcore/grpc/test-services/sample/Tests/Server/IntegrationTests/MockedGreeterServiceTests.cs#L69-L86) integration test does not build out-of-the-box.

## How to reproduce

1. Open the repository in a GitHub CodeSpace or Visual Studio Code.

1. Move to the GRPC sample tests directory

    ```plaintext
    cd aspnetcore/grpc/test-services/sample/Tests
    ```

1. Attempt to run the tests

    ```plaintext
    dotnet test
    ```

1. You should receive a build error on `MockedGreeterServiceTests.cs`

    ```plaintext
    /workspaces/AspNetCore.Docs/aspnetcore/grpc/test-services/sample/Tests/Server/IntegrationTests/MockedGreeterServiceTests.cs(69,10): error CS0616: 'Test' is not an attribute class [/workspaces/AspNetCore.Docs/aspnetcore/grpc/test-services/sample/Tests/Tests.csproj]
    ```

## The Error

It smells like the [`Assert.Fail()`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.testtools.unittesting.assert.fail?view=visualstudiosdk-2022#microsoft-visualstudio-testtools-unittesting-assert-fail) and [`StringAssert.Contains()`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.testtools.unittesting.stringassert.contains?view=visualstudiosdk-2022) assertions that come from the `Microsoft.VisualStudio.TestTools.UnitTesting` namespace that comes packaged with Visual Studio is not referenced in [Tests.csproj](https://github.com/dotnet/AspNetCore.Docs/blob/61d48b225d0611d176d6ad4367ea50ae841b30f6/aspnetcore/grpc/test-services/sample/Tests/Tests.csproj). 

https://github.com/dotnet/AspNetCore.Docs/blob/61d48b225d0611d176d6ad4367ea50ae841b30f6/aspnetcore/grpc/test-services/sample/Tests/Server/IntegrationTests/MockedGreeterServiceTests.cs#L69-L86

## Potential Fix

We could probably instead use xUnit's exception assertions given that the rest of the tests in this sample use xUnit's `[Fact]`.

# Software versions

Check the .NET target framework(s) being used, and include the version number(s).

* [x] .NET SDK 6.0.400

<details>
<summary><strong>dotnet --info output</strong></summary>

```console
.NET SDK (reflecting any global.json):
 Version:   6.0.400
 Commit:    7771abd614

Runtime Environment:
 OS Name:     debian
 OS Version:  11
 OS Platform: Linux
 RID:         debian.11-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.400/

global.json file:
  Not found

Host:
  Version:      6.0.8
  Architecture: x64
  Commit:       55fb7ef977

.NET SDKs installed:
  6.0.400 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```
</details>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24ad662e-1855-15bb-8e98-698e8c29b7fb
* Version Independent ID: 24ad662e-1855-15bb-8e98-698e8c29b7fb
* Content: [Test gRPC services in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/grpc/test-services?view=aspnetcore-6.0)
* Content Source: [aspnetcore/grpc/test-services.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/test-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

### PR DESCRIPTION
**Pull request by glennmusa**
Fixes #26937

This test fails to build when using Visual Studio Code or a CodeSpace. This change makes use of xUnit's exception assertions that are already included in the .csproj to conduct the same test.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=26938) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=26938) before we can accept your contribution.<br/><br/>:x: glennmusa [sign now](https://cla.dotnetfoundation.org/dotnet/AspNetCore.Docs?pullRequest=26938)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/AspNetCore.Docs?pullRequest=26938) it.</sub>

File: aspnetcore/grpc/test-services/sample/Tests/Server/IntegrationTests/MockedGreeterServiceTests.cs [hunk 1]
```diff
@@ -66,23 +66,19 @@ public async Task SayHelloUnaryTest_MockGreeter_Success()
...
-            {
-                await client.SayHelloUnaryAsync(new HelloRequest { Name = "" });
-                Assert.Fail();
-            }
-            catch (RpcException ex)
-            {
-                // Assert
-                StringAssert.Contains("Name not provided.", ex.Status.Detail);
-            }
+            var exception = await Record.ExceptionAsync(async () =>
```
Comment (JamesNK) [inline aspnetcore/grpc/test-services/sample/Tests/Server/IntegrationTests/MockedGreeterServiceTests.cs:76]:
```suggestion
            var exception = await Assert.ThrowsAsync<RpcException>(async () =>
```

File: aspnetcore/grpc/test-services/sample/Tests/Server/IntegrationTests/MockedGreeterServiceTests.cs [hunk 2]
```diff
@@ -66,23 +66,19 @@ public async Task SayHelloUnaryTest_MockGreeter_Success()
...
+                await client.SayHelloUnaryAsync(new HelloRequest { Name = "" }));
+
+            // Assert
+            Assert.IsType<RpcException>(exception);
```
Comment (JamesNK) [inline aspnetcore/grpc/test-services/sample/Tests/Server/IntegrationTests/MockedGreeterServiceTests.cs:80]:
```suggestion
```

**Review by JamesNK — APPROVED** [review]

**Comment by JamesNK** [comment]
Thanks for the fix!
